# Function 5

You’re tasked with optimising a four-variable black-box function that represents the yield of a chemical process in a factory. The function is typically unimodal, with a single peak where yield is maximised.

Your goal is to find the optimal combination of chemical inputs that delivers the highest possible yield, using systematic exploration and optimisation methods.

In [1]:
FUNCTION_ID=5

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [2]:
x, y = hd.load_and_append(5, 1)

Retrieving inputs/outputs for function 5, week 1

In [3]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (20, 4)
Outputs shape: (20,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332

In [4]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=100
xi = 0.005

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.244602-0.830057-0.890769-0.874939

## Week 2

In [5]:
x, y = hd.load_and_append(5, 2)

Retrieving inputs/outputs for function 5, week 2
*** Loading new inputs for function 5, week 2 ***

In [6]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (21, 4)
Outputs shape: (21,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.219411  0.830037  0.858036  0.813264   694.789851

In [7]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=0.1
xi = 0.01

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi,
    length_scale=length_scale
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.238685-0.844029-0.876306-0.899370

* ei, found a high peak, better to capitalize and reduce exploration

## Week 3

In [8]:
x, y = hd.load_and_append(5, 3)

Retrieving inputs/outputs for function 5, week 3
*** Loading new inputs for function 5, week 3 ***

In [9]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (22, 4)
Outputs shape: (22,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.219411  0.830037  0.858036  0.813264   694.789851
21  0.267410  0.864819  0.926213  0.922267  1698.660010

In [10]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=0.25
xi = 0.001

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi,
    length_scale=length_scale
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.334040-0.869924-1.000000-0.954533

## Week 4

In [11]:
x, y = hd.load_and_append(5, 4)

Retrieving inputs/outputs for function 5, week 4
*** Loading new inputs for function 5, week 4 ***

In [12]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (23, 4)
Outputs shape: (23,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.219411  0.830037  0.858036  0.813264   694.789851
21  0.267410  0.864819  0.926213  0.922267  1698.660010
22  0.363846  0.907131  0.951580  0.939799  2334.963703

In [13]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=0.25
xi = 0.001
n_candidates=20000
upper_bound=0.999999

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates, upper_bound=upper_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.402534-0.921335-0.940362-0.971018

* ei again, seemed to be reaching the peak
* scaling is optional, but im choosing to leave it for now
* upped n_candidates to 20000, for good measure (might be the standard from now on)
* massive jump this time, quite happy with this particular function
* had to  lower the upper bound when proposing, it was opting 1 for x3 and x4

## Week 5

In [14]:
x, y = hd.load_and_append(5, 5)

Retrieving inputs/outputs for function 5, week 5
*** Loading new inputs for function 5, week 5 ***

In [15]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (24, 4)
Outputs shape: (24,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.219411  0.830037  0.858036  0.813264   694.789851
21  0.267410  0.864819  0.926213  0.922267  1698.660010
22  0.363846  0.907131  0.951580  0.939799  2334.963703
23  0.418578  0.927686  0.999999  0.999999  3692.327806

In [16]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=0.25
xi = 0.001
n_candidates=20000
upper_bound=0.999999

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates, upper_bound=upper_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.432368-0.931859-0.999999-0.999999

* ei again, output is increasing by the thousands, very happy with this
* tiny xi, heavy exploitation
* length scale @ 0.25 keeps predictions smooth, preventing wild jumps in less sampled regions

## Week 6

In [17]:
x, y = hd.load_and_append(5, 6)

Retrieving inputs/outputs for function 5, week 6
*** Loading new inputs for function 5, week 6 ***

In [18]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (25, 4)
Outputs shape: (25,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.219411  0.830037  0.858036  0.813264   694.789851
21  0.267410  0.864819  0.926213  0.922267  1698.660010
22  0.363846  0.907131  0.951580  0.939799  2334.963703
23  0.418578  0.927686  0.999999  0.999999  3692.327806
24  0.427959  0.930822  0.999999  0.999999  3733.984488

In [19]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=0.25
xi = 0.002
n_candidates=20000
upper_bound=0.999999

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates, upper_bound=upper_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.448172-0.938855-0.999999-0.999999

* ei again, it is stabilizing to high 3k
* one more attempt at slightly raising xi
    * want to see if direction is still going upward

## Week 7

In [20]:
x, y = hd.load_and_append(5, 7)

Retrieving inputs/outputs for function 5, week 7
*** Loading new inputs for function 5, week 7 ***

In [21]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (26, 4)
Outputs shape: (26,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.219411  0.830037  0.858036  0.813264   694.789851
21  0.267410  0.864819  0.926213  0.922267  1698.660010
22  0.363846  0.907131  0.951580  0.939799  2334.963703
23  0.418578  0.927686  0.999999  0.999999  3692.327806
24  0.427959  0.930822  0.999999  0.999999  3733.984488
25  0.445791  0.936160  0.999999  0.999999  3809.891107

In [22]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=0.25
xi = 0.002
n_candidates=20000
upper_bound=0.999999

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates, upper_bound=upper_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.466576-0.941555-0.999999-0.999999

## Week 8

In [23]:
x, y = hd.load_and_append(5, 8)

Retrieving inputs/outputs for function 5, week 8
*** Loading new inputs for function 5, week 8 ***

In [24]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (27, 4)
Outputs shape: (27,)

          x1        x2        x3        x4       output
0   0.191447  0.038193  0.607418  0.414584    64.443440
1   0.758653  0.536518  0.656000  0.360342    18.301380
2   0.438350  0.804340  0.210245  0.151295     0.112940
3   0.706051  0.534192  0.264243  0.482088     4.210898
4   0.836478  0.193610  0.663893  0.785649   258.370525
5   0.683432  0.118663  0.829046  0.567577    78.434389
6   0.553621  0.667350  0.323806  0.814870    57.571537
7   0.352356  0.322242  0.116979  0.473113   109.571876
8   0.153786  0.729382  0.422598  0.443074     8.847992
9   0.463442  0.630025  0.107906  0.957644   233.223610
10  0.677491  0.358510  0.479592  0.072880    24.423088
11  0.583973  0.147243  0.348097  0.428615    64.420147
12  0.306889  0.316878  0.622634  0.095399    63.476716
13  0.511142  0.817957  0.728710  0.112354    79.729130
14  0.438933  0.774092  0.378167  0.933696   355.806818
15  0.224189  0.846480  0.879484  0.878516  1088.859618
16  0.725262  0.479870  0.088947  0.759760    28.866752
17  0.355482  0.639619  0.417618  0.122604    45.181570
18  0.119879  0.862540  0.643331  0.849804   431.612757
19  0.126885  0.153430  0.770162  0.190518     9.972332
20  0.219411  0.830037  0.858036  0.813264   694.789851
21  0.267410  0.864819  0.926213  0.922267  1698.660010
22  0.363846  0.907131  0.951580  0.939799  2334.963703
23  0.418578  0.927686  0.999999  0.999999  3692.327806
24  0.427959  0.930822  0.999999  0.999999  3733.984488
25  0.445791  0.936160  0.999999  0.999999  3809.891107
26  0.471987  0.943441  0.999999  0.999999  3923.016866

In [36]:
acquisition = "ei"
beta = 1.5
noise = 1e-6
length_scale=0.25
xi = 0.002
n_candidates=20000
upper_bound=0.999999

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates, upper_bound=upper_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.512656-0.953057-0.999999-0.999999