# Function 1

Detect likely contamination sources in a two-dimensional area, such as a radiation field, where only proximity yields a non-zero reading. The system uses Bayesian optimisation to tune detection parameters and reliably identify both strong and weak sources.

In [1]:
FUNCTION_ID=1

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [2]:
x, y = hd.load_and_append(1, 1)

Retrieving inputs/outputs for function 1, week 1

In [3]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (10, 2)
Outputs shape: (10,)

         x1        x2         output
0  0.319404  0.762959   1.322677e-79
1  0.574329  0.879898   1.033078e-46
2  0.731024  0.733000   7.710875e-16
3  0.840353  0.264732  3.341771e-124
4  0.650114  0.681526  -3.606063e-03
5  0.410437  0.147554  -2.159249e-54
6  0.312691  0.078723  -2.089093e-91
7  0.683418  0.861057   2.535001e-40
8  0.082507  0.403488   3.606771e-81
9  0.883890  0.582254   6.229856e-48

In [4]:
acquisition = "ucb"
beta = 1.96
noise = 1e-6
length_scale=100

bo = op.BayesianOptimizer(x, y, acquisition=acquisition, beta=beta, noise=noise, length_scale=length_scale)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.000418-0.009972

## Week 2

In [5]:
x, y = hd.load_and_append(1, 2)

Retrieving inputs/outputs for function 1, week 2
*** Loading new inputs for function 1, week 2 ***

In [6]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (11, 2)
Outputs shape: (11,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39

In [7]:
acquisition = "ucb"
beta = 1.96
noise = 1e-6
length_scale=0.01

bo = op.BayesianOptimizer(x, y, acquisition=acquisition, beta=beta, noise=noise, length_scale=length_scale)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.684539-0.968059

It seems like this week, it is still in the exploration phase, giving me various options ranging from the highs and lows

## Week 3

In [8]:
x, y = hd.load_and_append(1, 3)

Retrieving inputs/outputs for function 1, week 3
*** Loading new inputs for function 1, week 3 ***

In [9]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (12, 2)
Outputs shape: (12,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51

In [10]:
acquisition = "ucb"
beta = 3
noise = 1e-6
length_scale=0.2

bo = op.BayesianOptimizer(x, y, acquisition=acquisition, beta=beta, noise=noise, length_scale=length_scale)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.010895-0.998506

## Week 4

In [11]:
x, y = hd.load_and_append(1, 4)

Retrieving inputs/outputs for function 1, week 4
*** Loading new inputs for function 1, week 4 ***

In [12]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (13, 2)
Outputs shape: (13,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51
12  0.007178  0.993814   0.000000e+00

In [13]:
acquisition = "ucb"
beta = 1
length_scale=0.008
scale=0.05
n_candidates = 50000
acquisition = 'ei'
xi=0.005

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale=length_scale,
    xi=xi)
next = bo.propose(
    n_candidates, 
    scale=length_scale)

op.print_next_submission(next)

The next points to be submitted are:
0.762875-0.758716

This week, I will change to EI
* it seems as if exploring the 'corner' region as led to a dead center result.
* hypothesis: switching to EI might help exploit point index 4
* outcome: it did not exploit index 4, instead it focused on other corner region. even with an aggressive xi to encourage exploration, that region is filled with uncertainty
* I will submit these points, to better figure out what direction we are heading with this
* i had time to revision it, length scale has be decreased, to keep the candidates closer to the best observation
* xi is smaller still, to improve the best point rather than explore
* candidates have been increased

## Week 5

In [14]:
x, y = hd.load_and_append(1, 5)

Retrieving inputs/outputs for function 1, week 5
*** Loading new inputs for function 1, week 5 ***

In [15]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (14, 2)
Outputs shape: (14,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51
12  0.007178  0.993814   0.000000e+00
13  0.707295  0.721529   8.047078e-11

In [16]:
acquisition = "ucb"
beta = 1
length_scale=0.04
scale=0.03
n_candidates = 50000
acquisition = 'ei'
xi=0.002

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale=length_scale,
    xi=xi)
next = bo.propose(
    n_candidates, 
    scale=scale)

op.print_next_submission(next)

The next points to be submitted are:
0.678058-0.784092

This week, EI is still the preferred acquisition function
* length scale has been increased slightly
    * implication being that GP slightly connects these points
* scale reduced, reduces exploration
* xi reduced for strong exploitation

## Week 6

In [17]:
x, y = hd.load_and_append(1, 6)

Retrieving inputs/outputs for function 1, week 6
*** Loading new inputs for function 1, week 6 ***

In [18]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (15, 2)
Outputs shape: (15,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51
12  0.007178  0.993814   0.000000e+00
13  0.707295  0.721529   8.047078e-11
14  0.675585  0.784173  -2.613236e-19

In [19]:
acquisition = "ei"
beta = 1
length_scale=0.04
scale=0.03
n_candidates = 50000
acquisition = 'ei'
xi=0.002

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale=length_scale,
    xi=xi)
next = bo.propose(
    n_candidates, 
    scale=scale)

op.print_next_submission(next)

The next points to be submitted are:
0.790177-0.628243

This week, EI is still the preferred acquisition function
* no values changes
* proposed seem in line with expected maximum

## Week 7

In [20]:
x, y = hd.load_and_append(1, 7)

Retrieving inputs/outputs for function 1, week 7
*** Loading new inputs for function 1, week 7 ***

In [21]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (16, 2)
Outputs shape: (16,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51
12  0.007178  0.993814   0.000000e+00
13  0.707295  0.721529   8.047078e-11
14  0.675585  0.784173  -2.613236e-19
15  0.789539  0.623182   1.795145e-18

In [22]:
acquisition = "ei"
beta = 1
length_scale=0.03
scale=0.02
n_candidates = 50000
acquisition = 'ei'
xi=0.002

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale=length_scale,
    xi=xi)
next = bo.propose(
    n_candidates, 
    scale=scale)

op.print_next_submission(next)

The next points to be submitted are:
0.808589-0.735415

## Week 8

In [23]:
x, y = hd.load_and_append(1, 8)

Retrieving inputs/outputs for function 1, week 8
*** Loading new inputs for function 1, week 8 ***

In [24]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (17, 2)
Outputs shape: (17,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51
12  0.007178  0.993814   0.000000e+00
13  0.707295  0.721529   8.047078e-11
14  0.675585  0.784173  -2.613236e-19
15  0.789539  0.623182   1.795145e-18
16  0.746588  0.672274  -3.293389e-14

In [25]:
acquisition = "ei"
beta = 1
length_scale=0.03
scale=0.02
n_candidates = 50000
acquisition = 'ei'
xi=0.002

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale=length_scale,
    xi=xi)

next = bo.propose(
    n_candidates, 
    scale=scale)

op.print_next_submission(next)

The next points to be submitted are:
0.774272-0.785096

## Week 9

In [26]:
x, y = hd.load_and_append(1, 9)

Retrieving inputs/outputs for function 1, week 9
*** Loading new inputs for function 1, week 9 ***

In [27]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (18, 2)
Outputs shape: (18,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51
12  0.007178  0.993814   0.000000e+00
13  0.707295  0.721529   8.047078e-11
14  0.675585  0.784173  -2.613236e-19
15  0.789539  0.623182   1.795145e-18
16  0.746588  0.672274  -3.293389e-14
17  0.725990  0.804668  -7.372528e-29

In [28]:
acquisition = "ei"
beta = 1
length_scale=0.03
scale=0.02
n_candidates = 50000
acquisition = 'ei'
xi=0.002

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale=length_scale,
    xi=xi)

next = bo.propose(
    n_candidates, 
    scale=scale)

op.print_next_submission(next)

The next points to be submitted are:
0.785331-0.712980

## Week 10

In [29]:
x, y = hd.load_and_append(1, 10)

Retrieving inputs/outputs for function 1, week 10
*** Loading new inputs for function 1, week 10 ***

In [30]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (19, 2)
Outputs shape: (19,)

          x1        x2         output
0   0.319404  0.762959   1.322677e-79
1   0.574329  0.879898   1.033078e-46
2   0.731024  0.733000   7.710875e-16
3   0.840353  0.264732  3.341771e-124
4   0.650114  0.681526  -3.606063e-03
5   0.410437  0.147554  -2.159249e-54
6   0.312691  0.078723  -2.089093e-91
7   0.683418  0.861057   2.535001e-40
8   0.082507  0.403488   3.606771e-81
9   0.883890  0.582254   6.229856e-48
10  0.197599  0.492871   3.681503e-39
11  0.520896  0.171238   2.346948e-51
12  0.007178  0.993814   0.000000e+00
13  0.707295  0.721529   8.047078e-11
14  0.675585  0.784173  -2.613236e-19
15  0.789539  0.623182   1.795145e-18
16  0.746588  0.672274  -3.293389e-14
17  0.725990  0.804668  -7.372528e-29
18  0.791944  0.747999   4.327200e-30

In [31]:
acquisition = "ei"
beta = 1
length_scale=0.03
scale=0.02
n_candidates = 50000
acquisition = 'ei'
xi=0.002

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale=length_scale,
    xi=xi)

next = bo.propose(
    n_candidates, 
    scale=scale)

op.print_next_submission(next)

The next points to be submitted are:
0.633134-0.756059