# Function 8

You’re optimising an eight-dimensional black-box function, where each of the eight input parameters affects the output, but the internal mechanics are unknown.

Your objective is to find the parameter combination that maximises the function’s output, such as performance, efficiency or validation accuracy. Because the function is high-dimensional and likely complex, global optimisation is hard, so identifying strong local maxima is often a practical strategy.

For example, imagine you’re tuning an ML model with eight hyperparameters: learning rate, batch size, number of layers, dropout rate, regularisation strength, activation function (numerically encoded), optimiser type (encoded) and initial weight range. Each input set returns a single validation accuracy score between 0 and 1. Your goal is to maximise this score.

In [2]:
FUNCTION_ID=8

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [3]:
x, y = hd.load_and_append(8, 1)

Retrieving inputs/outputs for function 8, week 1

In [4]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (40, 8)
Outputs shape: (40,)

,learning_rate,batch_size,num_layers,dropout_rate,regularisation_strength,activation_function,optimiser_type,initial_weight_range,output
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005

In [5]:
acquisition = "ucb"
beta = 3
noise = 1e-6
xi = 0.005
length_scale = 0.7

bo = op.BayesianOptimizer(
    x, 
    y,
    acquisition=acquisition, 
    beta=beta, 
    noise=noise
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.473269-0.854477-0.603968-0.023765-0.818002-0.941128-0.046375-0.427309

## Week 2

In [6]:
x, y = hd.load_and_append(8, 2)

Retrieving inputs/outputs for function 8, week 2
*** Loading new inputs for function 8, week 2 ***

In [7]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (41, 8)
Outputs shape: (41,)

,learning_rate,batch_size,num_layers,dropout_rate,regularisation_strength,activation_function,optimiser_type,initial_weight_range,output
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.122218,0.102157,0.123144,0.099093,0.415268,0.446588,0.071479,0.269864,9.873195

In [8]:
acquisition = "ucb"
beta = 3
noise = 1e-4
xi = 0.005
length_scale = 0.7

bo = op.BayesianOptimizer(
    x, 
    y,
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi, 
    length_scale=length_scale
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.083845-0.373728-0.217920-0.387493-0.481370-0.315045-0.465730-0.309715

easy, i think its a matter of fine tuning beta for exploration

## Week 3

In [9]:
x, y = hd.load_and_append(8, 3)

Retrieving inputs/outputs for function 8, week 3
*** Loading new inputs for function 8, week 3 ***

In [10]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (42, 8)
Outputs shape: (42,)

,learning_rate,batch_size,num_layers,dropout_rate,regularisation_strength,activation_function,optimiser_type,initial_weight_range,output
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.122218,0.102157,0.123144,0.099093,0.415268,0.446588,0.071479,0.269864,9.873195
41,0.145103,0.387915,0.046081,0.245527,0.531755,0.771797,0.197713,0.805155,9.795005

In [12]:
acquisition = "ei"
beta = 3
noise = 1e-6
xi = 0.01
length_scale = 0.7
n_candidates=20000
length_scale_bounds=(0.1, 2.0)

bo = op.BayesianOptimizer(
    x, 
    y,
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi, 
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.086276-0.214760-0.215622-0.130362-0.541503-0.534297-0.242802-0.457655

* switched to ei
* lower beta value for ucb, to balances more exporing while capitalizing on promising regions, not as aggressive as week 2
* lower length scale, and added length scale bounds, prevents underfitting too much
* reduced noise
* 0.141077-0.258349-0.159880-0.254071-0.539345-0.660506-0.326839-0.704651 as sample points with ucb

## Week 4

In [13]:
x, y = hd.load_and_append(8, 4)

Retrieving inputs/outputs for function 8, week 4
*** Loading new inputs for function 8, week 4 ***

In [14]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (43, 8)
Outputs shape: (43,)

,learning_rate,batch_size,num_layers,dropout_rate,regularisation_strength,activation_function,optimiser_type,initial_weight_range,output
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.122218,0.102157,0.123144,0.099093,0.415268,0.446588,0.071479,0.269864,9.873195
41,0.145103,0.387915,0.046081,0.245527,0.531755,0.771797,0.197713,0.805155,9.795005
42,0.114094,0.215085,0.137667,0.263595,0.646836,0.515484,0.308092,0.523793,9.946369

In [15]:
acquisition = "ei"
beta = 3
noise = 1e-6
xi = 0.01
length_scale = 0.3
n_candidates=20000
length_scale_bounds=(0.1, 2.0)

bo = op.BayesianOptimizer(
    x, 
    y,
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi, 
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.180371-0.159613-0.167814-0.322947-0.435884-0.584317-0.264719-0.424376

* committing to ei, the points seem consistent, and outputs are clearly going in the right direction
* next week i will focus on exploration, exploring another local maxima. im interested in point index 14, will try to focus in on that, find another maxima
* all hyperparams are the same as last week, want to see the direction for this week

## Week 5

In [16]:
x, y = hd.load_and_append(8, 5)

Retrieving inputs/outputs for function 8, week 5
*** Loading new inputs for function 8, week 5 ***

In [17]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (44, 8)
Outputs shape: (44,)

,learning_rate,batch_size,num_layers,dropout_rate,regularisation_strength,activation_function,optimiser_type,initial_weight_range,output
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.122218,0.102157,0.123144,0.099093,0.415268,0.446588,0.071479,0.269864,9.873195
41,0.145103,0.387915,0.046081,0.245527,0.531755,0.771797,0.197713,0.805155,9.795005
42,0.114094,0.215085,0.137667,0.263595,0.646836,0.515484,0.308092,0.523793,9.946369
43,0.164149,0.211383,0.105835,0.223952,0.407767,0.520755,0.342990,0.446462,9.860177

In [18]:
acquisition = "ei"
beta = 3
noise = 1e-6
xi = 0.02
length_scale = 0.3
n_candidates=20000
length_scale_bounds=(0.1, 1.6)

bo = op.BayesianOptimizer(
    x, 
    y,
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi, 
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.080754-0.157883-0.224703-0.182013-0.677873-0.546979-0.208276-0.480955

* committed to ei
* xi slightly increased, preserve exploitation, but allows some wiggle room for exploring
* length scale reduced, can capture more sudden changes in high dimensional function

## Week 6

In [20]:
x, y = hd.load_and_append(8, 6)

Retrieving inputs/outputs for function 8, week 6
*** Loading new inputs for function 8, week 6 ***

In [ ]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (44, 8)
Outputs shape: (44,)

,learning_rate,batch_size,num_layers,dropout_rate,regularisation_strength,activation_function,optimiser_type,initial_weight_range,output
0,0.604994,0.292215,0.908453,0.355506,0.201669,0.575338,0.310311,0.734281,7.398721
1,0.178007,0.566223,0.994862,0.210325,0.320153,0.707909,0.635384,0.107132,7.005227
2,0.009077,0.811626,0.520520,0.075687,0.265112,0.091652,0.592415,0.367320,8.459482
3,0.506028,0.653730,0.363411,0.177981,0.093728,0.197425,0.755827,0.292472,8.284008
4,0.359909,0.249076,0.495997,0.709215,0.114987,0.289207,0.557295,0.593882,8.606117
5,0.778818,0.003419,0.337983,0.519528,0.820907,0.537247,0.551347,0.660032,8.541748
6,0.908649,0.062250,0.238260,0.766604,0.132336,0.990244,0.688068,0.742496,7.327435
7,0.586371,0.880736,0.745021,0.546035,0.009649,0.748992,0.230907,0.097916,7.299872
8,0.761137,0.854672,0.382124,0.337352,0.689708,0.309853,0.631380,0.041956,7.957875
9,0.984933,0.699506,0.998885,0.180148,0.580143,0.231087,0.490827,0.313683,5.592193
10,0.112071,0.437736,0.596599,0.592776,0.226982,0.410105,0.921238,0.674753,7.854541
11,0.791888,0.576191,0.694528,0.283424,0.136755,0.279162,0.842767,0.625328,6.791986
12,0.143550,0.937415,0.232325,0.009043,0.414579,0.409325,0.553779,0.205841,8.976554
13,0.769917,0.458759,0.559000,0.694604,0.503199,0.728346,0.784254,0.663131,7.379083
14,0.056447,0.065956,0.022929,0.038786,0.403935,0.801055,0.488307,0.893085,9.598482
15,0.862437,0.482734,0.281869,0.544102,0.887490,0.382655,0.601902,0.476462,8.159983
16,0.351512,0.590065,0.909436,0.678408,0.212826,0.088460,0.410153,0.195724,7.131624
17,0.735904,0.034612,0.728030,0.147427,0.295743,0.445117,0.975180,0.374340,6.767963
18,0.680294,0.255105,0.862188,0.134396,0.326329,0.287907,0.435010,0.364200,7.433744
19,0.044329,0.013581,0.258198,0.577644,0.051280,0.158563,0.591030,0.077953,9.013075
20,0.778345,0.751146,0.314142,0.902986,0.335382,0.386323,0.748972,0.988755,7.310894
21,0.898887,0.523642,0.876783,0.218696,0.900261,0.282766,0.911078,0.472398,5.841067
22,0.145120,0.119328,0.420888,0.387609,0.155423,0.875172,0.510560,0.728611,9.141639
23,0.338954,0.566932,0.376751,0.098916,0.659452,0.245548,0.762483,0.732153,8.817558
24,0.176150,0.293961,0.975680,0.793936,0.923401,0.030842,0.803255,0.595898,6.451943
25,0.028947,0.028279,0.481372,0.613175,0.672660,0.022113,0.601483,0.524885,8.830745
26,0.192640,0.630677,0.416796,0.490529,0.796086,0.654567,0.276241,0.295518,9.344274
27,0.943185,0.218851,0.721184,0.424597,0.986902,0.535183,0.714743,0.960094,6.887846
28,0.532721,0.833693,0.071399,0.116811,0.730693,0.937376,0.866508,0.127902,8.042213
29,0.447096,0.843953,0.729546,0.639151,0.409287,0.132646,0.035909,0.446838,7.692368
30,0.382225,0.557136,0.853102,0.333796,0.265721,0.480873,0.237647,0.768632,7.923759
31,0.532820,0.862308,0.538267,0.049443,0.719701,0.906706,0.108231,0.525348,8.421759
32,0.394865,0.331802,0.740754,0.697862,0.737404,0.783777,0.254495,0.871146,8.278062
33,0.985945,0.873054,0.070393,0.053587,0.734153,0.520259,0.811040,0.103360,7.113457
34,0.964573,0.973980,0.663753,0.662216,0.673122,0.905238,0.458875,0.560918,6.402588
35,0.472071,0.168203,0.086428,0.452656,0.480619,0.622439,0.928974,0.112536,8.472936
36,0.856007,0.638894,0.326192,0.668503,0.240298,0.210299,0.167546,0.963590,7.977685
37,0.810032,0.635046,0.269548,0.869605,0.661922,0.252259,0.765670,0.890549,7.460872
38,0.796253,0.007037,0.355697,0.487566,0.740520,0.706650,0.992914,0.381734,7.436594
39,0.481245,0.102461,0.219486,0.677322,0.247509,0.244341,0.163825,0.715962,9.183005
40,0.122218,0.102157,0.123144,0.099093,0.415268,0.446588,0.071479,0.269864,9.873195
41,0.145103,0.387915,0.046081,0.245527,0.531755,0.771797,0.197713,0.805155,9.795005
42,0.114094,0.215085,0.137667,0.263595,0.646836,0.515484,0.308092,0.523793,9.946369
43,0.164149,0.211383,0.105835,0.223952,0.407767,0.520755,0.342990,0.446462,9.860177

In [98]:
acquisition = "ei"
beta = 0.25
noise = 1e-6
xi = 0.001
length_scale = 0.25
n_candidates=20000
length_scale_bounds=(0.05, 1.0)

bo = op.BayesianOptimizer(
    x, 
    y,
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.130849-0.237449-0.185727-0.167457-0.618164-0.581465-0.187019-0.530423

* committed to ei
* xi decreased, honing in on on around the indexes of the 40s
* index 42 has output 9.946369, EXTREMELY close to the maximum, im looking forward to seeing this