# Function 3

You’re working on a drug discovery project, testing combinations of three compounds to create a new medicine.

Each experiment is stored in initial_inputs.npy as a 3D array, where each row lists the amounts of the three compounds used. After each experiment, you record the number of adverse reactions, stored in initial_outputs.npy as a 1D array.

Your goal is to minimise side effects; in this competition, it is framed as maximisation by optimising a transformed output (e.g. the negative of side effects).

In [1]:
FUNCTION_ID=3

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [2]:
x, y = hd.load_and_append(3, 1)

Retrieving inputs/outputs for function 3, week 1

In [3]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (15, 3)
Outputs shape: (15,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758

In [4]:
acquisition = "ei"
beta = 1.96
noise = 1e-4
xi = 0.005
length_scale=100

bo = op.BayesianOptimizer(x, y, acquisition=acquisition, beta=beta, noise=noise, xi=xi)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.329810-0.293478-0.412215

## Week 2

In [5]:
x, y = hd.load_and_append(3, 2)

Retrieving inputs/outputs for function 3, week 2
*** Loading new inputs for function 3, week 2 ***

In [6]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (16, 3)
Outputs shape: (16,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482

In [7]:
acquisition = "ei"
beta = 1.96
noise = 1e-4
xi = 0.005
length_scale=100

bo = op.BayesianOptimizer(x, y, acquisition=acquisition, beta=beta, noise=noise, xi=xi)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.442072-0.598281-0.401418

* ei is still better choice here, still sparse coverage, still unknown, need to try to improve with the little attempts i have

## Week 3

In [8]:
x, y = hd.load_and_append(3, 3)

Retrieving inputs/outputs for function 3, week 3
*** Loading new inputs for function 3, week 3 ***

In [9]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (17, 3)
Outputs shape: (17,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985

In [10]:
acquisition = "ei"
beta = 1
noise = 1e-4
xi = 0.05
n_candidates=20000
lower_bound=0.2
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) # lets gp adapt smootheness as new data arrives, 


bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound, upper_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.800000-0.200000-0.734301

## Week 4

In [11]:
x, y = hd.load_and_append(3, 4)

Retrieving inputs/outputs for function 3, week 4
*** Loading new inputs for function 3, week 4 ***

In [12]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (18, 3)
Outputs shape: (18,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651

In [13]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.015
n_candidates=20000
scale=0.01
lower_bound=0
upper_bound=0.7
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound, upper_bound, scale)
op.print_next_submission(next)

The next points to be submitted are:
0.387844-0.258490-0.485603

* Last weeks results were 'bad' but good for confirming suspisions.
* I am moving more towards exploitation. In this field, even though I am not knowledgeable, I assume that drastically changing doses does not yield effective results, so concentrating on whats known to be good will be beneficial
* xi has been lowered
* tried to open the bounds slightly, still keeping me away from extremes. However, it is still pointing me to the edges, because the might think that we dont know much about the region. from analysing the points, high x1 and x3s have not produced good results, so i will refine the bounds to be tighter, to truly capitalize on the best observed region so far
* noise as also been increased, for less overconfident spikes, more stable ei behaviour, and smoother predictions
* i adjusted the propose function for ei, instead of generating random uniform candidates, for ei, i would generate random normal number, to exploit the bell curve more

## Week 5

In [14]:
x, y = hd.load_and_append(3, 5)

Retrieving inputs/outputs for function 3, week 5
*** Loading new inputs for function 3, week 5 ***

In [15]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (19, 3)
Outputs shape: (19,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459

In [16]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.025
n_candidates=30000
scale=0.02
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound, upper_bound, scale)
op.print_next_submission(next)

The next points to be submitted are:
0.354122-0.200281-0.501685

* Last weeks results were not bad
    *  xi raised
    *  lower bound raised
    *  upper bound raised
    *  scale increased

## Week 6

In [17]:
x, y = hd.load_and_append(3, 6)

Retrieving inputs/outputs for function 3, week 6
*** Loading new inputs for function 3, week 6 ***

In [18]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (20, 3)
Outputs shape: (20,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459
19  0.395487  0.215486  0.505019 -0.033865

In [19]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.001
n_candidates=50000
scale=0.01
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound=lower_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.382614-0.253344-0.482346

* Last weeks results gave one of the best results yet
* decreasing xi, focusing purely on exploitation
* n_candidates increased
* scale decreased even more

## Week 7

In [20]:
x, y = hd.load_and_append(3, 7)

Retrieving inputs/outputs for function 3, week 7
*** Loading new inputs for function 3, week 7 ***

In [21]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (21, 3)
Outputs shape: (21,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459
19  0.395487  0.215486  0.505019 -0.033865
20  0.366060  0.248513  0.496212 -0.031577

In [22]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.001
n_candidates=50000
scale=0.01
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound=lower_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.370128-0.246758-0.493886

## Week 8

In [23]:
x, y = hd.load_and_append(3, 8)

Retrieving inputs/outputs for function 3, week 8
*** Loading new inputs for function 3, week 8 ***

In [24]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (22, 3)
Outputs shape: (22,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459
19  0.395487  0.215486  0.505019 -0.033865
20  0.366060  0.248513  0.496212 -0.031577
21  0.389885  0.256107  0.494843 -0.033334

In [25]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.001
n_candidates=50000
scale=0.01
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound=lower_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.395705-0.256878-0.502324

## Week 9

In [26]:
x, y = hd.load_and_append(3, 9)

Retrieving inputs/outputs for function 3, week 9
*** Loading new inputs for function 3, week 9 ***

In [27]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (23, 3)
Outputs shape: (23,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459
19  0.395487  0.215486  0.505019 -0.033865
20  0.366060  0.248513  0.496212 -0.031577
21  0.389885  0.256107  0.494843 -0.033334
22  0.377007  0.247749  0.494434 -0.045498

In [28]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.001
n_candidates=50000
scale=0.01
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound=lower_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.386948-0.250832-0.483291

## Week 10

In [29]:
x, y = hd.load_and_append(3, 10)

Retrieving inputs/outputs for function 3, week 10
*** Loading new inputs for function 3, week 10 ***

In [30]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (24, 3)
Outputs shape: (24,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459
19  0.395487  0.215486  0.505019 -0.033865
20  0.366060  0.248513  0.496212 -0.031577
21  0.389885  0.256107  0.494843 -0.033334
22  0.377007  0.247749  0.494434 -0.045498
23  0.396566  0.251680  0.478761 -0.029272

In [31]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.001
n_candidates=50000
scale=0.01
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound=lower_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.390429-0.252932-0.483783

## Week 11

In [32]:
x, y = hd.load_and_append(3, 11)

Retrieving inputs/outputs for function 3, week 11
*** Loading new inputs for function 3, week 11 ***

In [33]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (25, 3)
Outputs shape: (25,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459
19  0.395487  0.215486  0.505019 -0.033865
20  0.366060  0.248513  0.496212 -0.031577
21  0.389885  0.256107  0.494843 -0.033334
22  0.377007  0.247749  0.494434 -0.045498
23  0.396566  0.251680  0.478761 -0.029272
24  0.381101  0.242732  0.492203 -0.049769

In [34]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.001
n_candidates=50000
scale=0.01
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound=lower_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.398893-0.254969-0.488801

## Week 12

In [35]:
x, y = hd.load_and_append(3, 12)

Retrieving inputs/outputs for function 3, week 12
*** Loading new inputs for function 3, week 12 ***

In [36]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (26, 3)
Outputs shape: (26,)

          x1        x2        x3    output
0   0.171525  0.343917  0.248737 -0.112122
1   0.242114  0.644074  0.272433 -0.087963
2   0.534906  0.398501  0.173389 -0.111415
3   0.492581  0.611593  0.340176 -0.034835
4   0.134622  0.219917  0.458206 -0.048008
5   0.345523  0.941360  0.269363 -0.110621
6   0.151837  0.439991  0.990882 -0.398926
7   0.645503  0.397143  0.919771 -0.113869
8   0.746912  0.284196  0.226300 -0.131461
9   0.170477  0.697032  0.149169 -0.094190
10  0.220549  0.297825  0.343555 -0.046947
11  0.666014  0.671985  0.246295 -0.105965
12  0.046809  0.231360  0.770618 -0.118048
13  0.600097  0.725136  0.066089 -0.036378
14  0.965995  0.861120  0.566829 -0.056758
15  0.509737  0.813011  0.044918 -0.049482
16  0.375431  0.293548  0.489997 -0.027985
17  0.779766  0.797921  0.781802 -0.108651
18  0.384766  0.246566  0.500749 -0.058459
19  0.395487  0.215486  0.505019 -0.033865
20  0.366060  0.248513  0.496212 -0.031577
21  0.389885  0.256107  0.494843 -0.033334
22  0.377007  0.247749  0.494434 -0.045498
23  0.396566  0.251680  0.478761 -0.029272
24  0.381101  0.242732  0.492203 -0.049769
25  0.407289  0.257594  0.507040 -0.031725

In [45]:
acquisition = "ei"
beta = 1
noise = 1e-3
xi = 0.001
n_candidates=50000
scale=0.01
lower_bound=0.15
upper_bound=0.8
length_scale=100
length_scale_bounds=(0.05, 2.0) 

bo = op.BayesianOptimizer(x, 
        y, 
        acquisition=acquisition, 
        beta=beta, 
        noise=noise, 
        xi=xi,
        length_scale_bounds=length_scale_bounds
    )

next = bo.propose(n_candidates, lower_bound=lower_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.395622-0.262869-0.520769