# Function 6

You’re optimising a cake recipe using a black-box function with five ingredient inputs, for example flour, sugar, eggs, butter and milk. Each recipe is evaluated with a combined score based on flavour, consistency, calories, waste and cost, where each factor contributes negative points as judged by an expert taster. This means the total score is negative by design. 

To frame this as a maximisation problem, your goal is to bring that score as close to zero as possible or, equivalently, to maximise the negative of the total sum.

In [1]:
FUNCTION_ID=6

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [2]:
x, y = hd.load_and_append(6, 1)

Retrieving inputs/outputs for function 6, week 1

In [3]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (20, 5)
Outputs shape: (20,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882

In [4]:
acquisition = "ei"
beta = 2.0
xi=0.005
noise = 1e-6
length_scale=0.1

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.392641-0.000000-0.722201-0.105099-0.035394

## Week 2

In [5]:
x, y = hd.load_and_append(6, 2)

Retrieving inputs/outputs for function 6, week 2
*** Loading new inputs for function 6, week 2 ***

In [6]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (21, 5)
Outputs shape: (21,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984

In [7]:
acquisition = "ei"
beta = 2.0
xi=0.005
noise = 1e-6
length_scale=0.1

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.000000-0.408817-0.142961-0.284526-0.033958

easy, i think its a matter of fine tuning hyperparameters and xi for exploration

## Week 3

In [8]:
x, y = hd.load_and_append(6, 3)

Retrieving inputs/outputs for function 6, week 3
*** Loading new inputs for function 6, week 3 ***

In [9]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (22, 5)
Outputs shape: (22,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495

In [10]:
acquisition = "ei"
beta = 2.0
xi=0.005
noise = 1e-6
length_scale=0.2

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.000000-0.000000-0.985860-0.986087-0.000000

* easy, i think its a matter of fine tuning hyperparameters and xi for exploration
* length_scale6=0.2 to let the GP be slightly smoother

## Week 4

In [11]:
x, y = hd.load_and_append(6, 4)

Retrieving inputs/outputs for function 6, week 4
*** Loading new inputs for function 6, week 4 ***

In [12]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (23, 5)
Outputs shape: (23,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516

In [13]:
acquisition = "ei"
beta = 2.0
xi=0.1
noise = 1e-4
length_scale=0.02
n_candidates=20000

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.637697-0.000000-0.704203-0.954623-0.355552

* increased xi and noise, making ei less greedy. using last week params gave horrible edge cases. not quite sure why, need to look into this (more realistic recipe combinations as opposed to 0,0,1,0,1)
* prevents proposals at the edge of the input space
* decreased length_scale. GP more sensitive to local variations in the data. fine tuning around promising areas rather than smoothing too much

## Week 5

In [14]:
x, y = hd.load_and_append(6, 5)

Retrieving inputs/outputs for function 6, week 5
*** Loading new inputs for function 6, week 5 ***

In [15]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (24, 5)
Outputs shape: (24,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324

In [16]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.25
n_candidates=20000
lower_bound=0.005000
upper_bound=0.999999

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.541142-0.005000-0.770005-0.877535-0.005000

* lowered noise
* lowered xi
* raised length scale
* added lower bound to avoid edges

## Week 6

In [17]:
x, y = hd.load_and_append(6, 6)

Retrieving inputs/outputs for function 6, week 6
*** Loading new inputs for function 6, week 6 ***

In [18]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (25, 5)
Outputs shape: (25,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261

In [19]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.005000
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.553972-0.226580-0.712233-0.711282-0.099950

* length scale incrased, added length scale bounds
    * with relatively less noise than function2, I don't mind the bound being slightly more sensitive to noise
* scale has been added, and increased by 0.05

## Week 7

In [20]:
x, y = hd.load_and_append(6, 7)

Retrieving inputs/outputs for function 6, week 7
*** Loading new inputs for function 6, week 7 ***

In [21]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (26, 5)
Outputs shape: (26,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261
25  0.533687  0.235070  0.672025  0.769338  0.084265 -0.294185

In [22]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.005000
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.516015-0.287743-0.668058-0.788637-0.075557

## Week 8

In [23]:
x, y = hd.load_and_append(6, 8)

Retrieving inputs/outputs for function 6, week 8
*** Loading new inputs for function 6, week 8 ***

In [24]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (27, 5)
Outputs shape: (27,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261
25  0.533687  0.235070  0.672025  0.769338  0.084265 -0.294185
26  0.478543  0.321728  0.645946  0.751962  0.068418 -0.115807

In [25]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.000001
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.402011-0.409273-0.650074-0.721921-0.000001

## Week 9

In [26]:
x, y = hd.load_and_append(6, 9)

Retrieving inputs/outputs for function 6, week 9
*** Loading new inputs for function 6, week 9 ***

In [27]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (28, 5)
Outputs shape: (28,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261
25  0.533687  0.235070  0.672025  0.769338  0.084265 -0.294185
26  0.478543  0.321728  0.645946  0.751962  0.068418 -0.115807
27  0.425858  0.358288  0.622078  0.716773  0.044031 -0.080502

In [28]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.000001
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.417377-0.384148-0.732256-0.734431-0.000001

## Week 10

In [29]:
x, y = hd.load_and_append(6, 10)

Retrieving inputs/outputs for function 6, week 10
*** Loading new inputs for function 6, week 10 ***

In [30]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (29, 5)
Outputs shape: (29,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261
25  0.533687  0.235070  0.672025  0.769338  0.084265 -0.294185
26  0.478543  0.321728  0.645946  0.751962  0.068418 -0.115807
27  0.425858  0.358288  0.622078  0.716773  0.044031 -0.080502
28  0.454102  0.411829  0.676872  0.758383  0.057069 -0.178209

In [31]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.000001
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.465523-0.312093-0.567508-0.713688-0.000001

## Week 11

In [32]:
x, y = hd.load_and_append(6, 11)

Retrieving inputs/outputs for function 6, week 11
*** Loading new inputs for function 6, week 11 ***

In [33]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (30, 5)
Outputs shape: (30,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261
25  0.533687  0.235070  0.672025  0.769338  0.084265 -0.294185
26  0.478543  0.321728  0.645946  0.751962  0.068418 -0.115807
27  0.425858  0.358288  0.622078  0.716773  0.044031 -0.080502
28  0.454102  0.411829  0.676872  0.758383  0.057069 -0.178209
29  0.454619  0.331846  0.627113  0.751103  0.014185 -0.216970

In [34]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.000001
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.409410-0.347035-0.601514-0.707656-0.093119

## Week 12

In [35]:
x, y = hd.load_and_append(6, 12)

Retrieving inputs/outputs for function 6, week 12
*** Loading new inputs for function 6, week 12 ***

In [36]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (31, 5)
Outputs shape: (31,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261
25  0.533687  0.235070  0.672025  0.769338  0.084265 -0.294185
26  0.478543  0.321728  0.645946  0.751962  0.068418 -0.115807
27  0.425858  0.358288  0.622078  0.716773  0.044031 -0.080502
28  0.454102  0.411829  0.676872  0.758383  0.057069 -0.178209
29  0.454619  0.331846  0.627113  0.751103  0.014185 -0.216970
30  0.468171  0.332353  0.650124  0.726286  0.156981 -0.151681

In [37]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.000001
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.429896-0.382153-0.552106-0.621129-0.119938

## Week 13

In [38]:
x, y = hd.load_and_append(6, 13)

Retrieving inputs/outputs for function 6, week 13
*** Loading new inputs for function 6, week 13 ***

In [39]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (32, 5)
Outputs shape: (32,)

       flour     sugar      eggs    butter      milk    output
0   0.728186  0.154693  0.732552  0.693997  0.056401 -0.714265
1   0.242384  0.844100  0.577809  0.679021  0.501953 -1.209955
2   0.729523  0.748106  0.679775  0.356552  0.671054 -1.672200
3   0.770620  0.114404  0.046780  0.648324  0.273549 -1.536058
4   0.618812  0.331802  0.187288  0.756238  0.328835 -0.829237
5   0.784958  0.910682  0.708120  0.959225  0.004911 -1.247049
6   0.145111  0.896685  0.896322  0.726272  0.236272 -1.233786
7   0.945069  0.288459  0.978806  0.961656  0.598016 -1.694343
8   0.125720  0.862725  0.028544  0.246605  0.751206 -2.571170
9   0.757594  0.355831  0.016523  0.434207  0.112433 -1.309116
10  0.536797  0.308781  0.411879  0.388225  0.522528 -1.144785
11  0.957740  0.235669  0.099146  0.156806  0.071317 -1.912677
12  0.629308  0.803484  0.811408  0.045613  0.110624 -1.622839
13  0.021735  0.428084  0.835939  0.489489  0.511082 -1.356682
14  0.439344  0.698924  0.426820  0.109476  0.877888 -2.018425
15  0.258906  0.793678  0.642114  0.196673  0.593103 -1.702558
16  0.432166  0.715618  0.341819  0.705000  0.614962 -1.294247
17  0.782880  0.536336  0.443284  0.859700  0.010326 -0.935757
18  0.921776  0.931871  0.414876  0.595057  0.735626 -2.155768
19  0.126679  0.291470  0.064528  0.680515  0.892819 -1.746882
20  0.443676  0.403472  0.212165  0.814086  0.177563 -0.653984
21  0.581071  0.083962  0.753693  0.767113  0.055051 -0.540495
22  0.664117  0.043549  0.978163  0.041147  0.987447 -2.433516
23  0.393100  0.037995  0.798822  0.550852  0.131015 -0.775324
24  0.531118  0.012107  0.762736  0.885909  0.030929 -0.746261
25  0.533687  0.235070  0.672025  0.769338  0.084265 -0.294185
26  0.478543  0.321728  0.645946  0.751962  0.068418 -0.115807
27  0.425858  0.358288  0.622078  0.716773  0.044031 -0.080502
28  0.454102  0.411829  0.676872  0.758383  0.057069 -0.178209
29  0.454619  0.331846  0.627113  0.751103  0.014185 -0.216970
30  0.468171  0.332353  0.650124  0.726286  0.156981 -0.151681
31  0.450256  0.346399  0.630172  0.635505  0.098237 -0.154226

In [41]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-6
length_scale=0.4
length_scale_bounds = (0.05, 1.0)
n_candidates=20000
lower_bound=0.000001
upper_bound=0.999999
scale=0.25

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    xi=xi,
    length_scale=length_scale,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound, upper_bound=upper_bound, scale=scale)
op.print_next_submission(next)

The next points to be submitted are:
0.394479-0.347143-0.617938-0.741530-0.141552