# Function 4

Address the challenge of optimally placing products across warehouses for a business with high online sales, where accurate calculations are costly and only feasible biweekly. To speed up decision-making, an ML model approximates these results within hours. The model has four hyperparameters to tune, and its output reflects the difference from the expensive baseline. Because the system is dynamic and full of local optima, it requires careful tuning and robust validation to find reliable, near-optimal solutions.

In [2]:
FUNCTION_ID=4

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [3]:
x, y = hd.load_and_append(4, 1)

Retrieving inputs/outputs for function 4, week 1

In [4]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (30, 4)
Outputs shape: (30,)

          x1        x2        x3        x4     output
0   0.896981  0.725628  0.175404  0.701694 -22.108288
1   0.889356  0.499588  0.539269  0.508783 -14.601397
2   0.250946  0.033693  0.145380  0.494932 -11.699932
3   0.346962  0.006250  0.760564  0.613024 -16.053765
4   0.124871  0.129770  0.384400  0.287076 -10.069633
5   0.801303  0.500231  0.706645  0.195103 -15.487083
6   0.247708  0.060445  0.042186  0.441324 -12.681685
7   0.746702  0.757092  0.369353  0.206566 -16.026400
8   0.400665  0.072574  0.886768  0.243842 -17.049235
9   0.626071  0.586751  0.438806  0.778858 -12.741766
10  0.957135  0.597644  0.766114  0.776210 -27.316396
11  0.732812  0.145250  0.476813  0.133366 -13.527649
12  0.655115  0.072392  0.687152  0.081517 -16.679115
13  0.219734  0.832031  0.482864  0.082569 -16.507159
14  0.488594  0.211965  0.939178  0.376192 -17.817999
15  0.167130  0.876555  0.217240  0.959801 -26.561821
16  0.216911  0.166086  0.241372  0.770062 -12.758324
17  0.387488  0.804532  0.751795  0.723827 -19.441558
18  0.985622  0.666933  0.156783  0.856535 -28.903274
19  0.037825  0.664853  0.161982  0.253924 -13.702747
20  0.683486  0.902770  0.335420  0.999483 -29.427091
21  0.170347  0.756959  0.276520  0.531231 -11.565742
22  0.859657  0.919592  0.206139  0.097797 -26.857786
23  0.282138  0.505987  0.530531  0.096302  -7.966775
24  0.326076  0.472367  0.453192  0.105887  -6.702089
25  0.948389  0.894513  0.851638  0.552196 -32.625660
26  0.664955  0.046566  0.116777  0.793718 -19.989498
27  0.577766  0.428772  0.425826  0.249007  -4.025542
28  0.738613  0.482103  0.709366  0.503970 -13.122782
29  0.854811  0.493965  0.735310  0.808092 -23.139428

In [5]:
acquisition = "ucb"
beta = 1.5
xi=0.005
noise = 1e-6
length_scale=100


bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.005221-0.257549-0.956803-0.983424

## Week 2

In [6]:
x, y = hd.load_and_append(4, 2)

Retrieving inputs/outputs for function 4, week 2
*** Loading new inputs for function 4, week 2 ***

In [7]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (31, 4)
Outputs shape: (31,)

          x1        x2        x3        x4     output
0   0.896981  0.725628  0.175404  0.701694 -22.108288
1   0.889356  0.499588  0.539269  0.508783 -14.601397
2   0.250946  0.033693  0.145380  0.494932 -11.699932
3   0.346962  0.006250  0.760564  0.613024 -16.053765
4   0.124871  0.129770  0.384400  0.287076 -10.069633
5   0.801303  0.500231  0.706645  0.195103 -15.487083
6   0.247708  0.060445  0.042186  0.441324 -12.681685
7   0.746702  0.757092  0.369353  0.206566 -16.026400
8   0.400665  0.072574  0.886768  0.243842 -17.049235
9   0.626071  0.586751  0.438806  0.778858 -12.741766
10  0.957135  0.597644  0.766114  0.776210 -27.316396
11  0.732812  0.145250  0.476813  0.133366 -13.527649
12  0.655115  0.072392  0.687152  0.081517 -16.679115
13  0.219734  0.832031  0.482864  0.082569 -16.507159
14  0.488594  0.211965  0.939178  0.376192 -17.817999
15  0.167130  0.876555  0.217240  0.959801 -26.561821
16  0.216911  0.166086  0.241372  0.770062 -12.758324
17  0.387488  0.804532  0.751795  0.723827 -19.441558
18  0.985622  0.666933  0.156783  0.856535 -28.903274
19  0.037825  0.664853  0.161982  0.253924 -13.702747
20  0.683486  0.902770  0.335420  0.999483 -29.427091
21  0.170347  0.756959  0.276520  0.531231 -11.565742
22  0.859657  0.919592  0.206139  0.097797 -26.857786
23  0.282138  0.505987  0.530531  0.096302  -7.966775
24  0.326076  0.472367  0.453192  0.105887  -6.702089
25  0.948389  0.894513  0.851638  0.552196 -32.625660
26  0.664955  0.046566  0.116777  0.793718 -19.989498
27  0.577766  0.428772  0.425826  0.249007  -4.025542
28  0.738613  0.482103  0.709366  0.503970 -13.122782
29  0.854811  0.493965  0.735310  0.808092 -23.139428
30  0.517002  0.541902  0.438844  0.403496  -3.092031

In [8]:
acquisition = "ucb"
beta = 1.5
xi=0.005
noise = 1e-6
length_scale=100


bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.004489-0.273534-0.926055-0.940035

* ucb still better choice. understanding prompt better now

## Week 3

In [9]:
x, y = hd.load_and_append(4, 3)

Retrieving inputs/outputs for function 4, week 3
*** Loading new inputs for function 4, week 3 ***

In [10]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (32, 4)
Outputs shape: (32,)

          x1        x2        x3        x4     output
0   0.896981  0.725628  0.175404  0.701694 -22.108288
1   0.889356  0.499588  0.539269  0.508783 -14.601397
2   0.250946  0.033693  0.145380  0.494932 -11.699932
3   0.346962  0.006250  0.760564  0.613024 -16.053765
4   0.124871  0.129770  0.384400  0.287076 -10.069633
5   0.801303  0.500231  0.706645  0.195103 -15.487083
6   0.247708  0.060445  0.042186  0.441324 -12.681685
7   0.746702  0.757092  0.369353  0.206566 -16.026400
8   0.400665  0.072574  0.886768  0.243842 -17.049235
9   0.626071  0.586751  0.438806  0.778858 -12.741766
10  0.957135  0.597644  0.766114  0.776210 -27.316396
11  0.732812  0.145250  0.476813  0.133366 -13.527649
12  0.655115  0.072392  0.687152  0.081517 -16.679115
13  0.219734  0.832031  0.482864  0.082569 -16.507159
14  0.488594  0.211965  0.939178  0.376192 -17.817999
15  0.167130  0.876555  0.217240  0.959801 -26.561821
16  0.216911  0.166086  0.241372  0.770062 -12.758324
17  0.387488  0.804532  0.751795  0.723827 -19.441558
18  0.985622  0.666933  0.156783  0.856535 -28.903274
19  0.037825  0.664853  0.161982  0.253924 -13.702747
20  0.683486  0.902770  0.335420  0.999483 -29.427091
21  0.170347  0.756959  0.276520  0.531231 -11.565742
22  0.859657  0.919592  0.206139  0.097797 -26.857786
23  0.282138  0.505987  0.530531  0.096302  -7.966775
24  0.326076  0.472367  0.453192  0.105887  -6.702089
25  0.948389  0.894513  0.851638  0.552196 -32.625660
26  0.664955  0.046566  0.116777  0.793718 -19.989498
27  0.577766  0.428772  0.425826  0.249007  -4.025542
28  0.738613  0.482103  0.709366  0.503970 -13.122782
29  0.854811  0.493965  0.735310  0.808092 -23.139428
30  0.517002  0.541902  0.438844  0.403496  -3.092031
31  0.536314  0.496395  0.373428  0.460871  -3.297565

In [11]:
acquisition = "ucb"
beta = 2.0
xi=0.005
noise = 1e-4
length_scale=100


bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.965296-0.005968-0.020610-0.023354

* switching between ucb and ei, to try and see robustness, both give similar regions? I need to understand this better

## Week 4

In [12]:
x, y = hd.load_and_append(4, 4)

Retrieving inputs/outputs for function 4, week 4
*** Loading new inputs for function 4, week 4 ***

In [13]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (33, 4)
Outputs shape: (33,)

          x1        x2        x3        x4     output
0   0.896981  0.725628  0.175404  0.701694 -22.108288
1   0.889356  0.499588  0.539269  0.508783 -14.601397
2   0.250946  0.033693  0.145380  0.494932 -11.699932
3   0.346962  0.006250  0.760564  0.613024 -16.053765
4   0.124871  0.129770  0.384400  0.287076 -10.069633
5   0.801303  0.500231  0.706645  0.195103 -15.487083
6   0.247708  0.060445  0.042186  0.441324 -12.681685
7   0.746702  0.757092  0.369353  0.206566 -16.026400
8   0.400665  0.072574  0.886768  0.243842 -17.049235
9   0.626071  0.586751  0.438806  0.778858 -12.741766
10  0.957135  0.597644  0.766114  0.776210 -27.316396
11  0.732812  0.145250  0.476813  0.133366 -13.527649
12  0.655115  0.072392  0.687152  0.081517 -16.679115
13  0.219734  0.832031  0.482864  0.082569 -16.507159
14  0.488594  0.211965  0.939178  0.376192 -17.817999
15  0.167130  0.876555  0.217240  0.959801 -26.561821
16  0.216911  0.166086  0.241372  0.770062 -12.758324
17  0.387488  0.804532  0.751795  0.723827 -19.441558
18  0.985622  0.666933  0.156783  0.856535 -28.903274
19  0.037825  0.664853  0.161982  0.253924 -13.702747
20  0.683486  0.902770  0.335420  0.999483 -29.427091
21  0.170347  0.756959  0.276520  0.531231 -11.565742
22  0.859657  0.919592  0.206139  0.097797 -26.857786
23  0.282138  0.505987  0.530531  0.096302  -7.966775
24  0.326076  0.472367  0.453192  0.105887  -6.702089
25  0.948389  0.894513  0.851638  0.552196 -32.625660
26  0.664955  0.046566  0.116777  0.793718 -19.989498
27  0.577766  0.428772  0.425826  0.249007  -4.025542
28  0.738613  0.482103  0.709366  0.503970 -13.122782
29  0.854811  0.493965  0.735310  0.808092 -23.139428
30  0.517002  0.541902  0.438844  0.403496  -3.092031
31  0.536314  0.496395  0.373428  0.460871  -3.297565
32  0.032597  0.410688  0.963138  0.948923 -31.317537

In [14]:
acquisition = "ei"
beta = 2.0
xi=0.01
noise = 1e-4
length_scale=100
length_scale_bounds=(0.08, 1.0)
n_candidates=20000

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.536960-0.505436-0.392102-0.436815

* switched to ei, after revloutionizing the function after function3, i decided to try and trust it.
* the points given seem to be fairly consistent, hopefully will be good
* length_scale_bounds also added, to avoid tiny fluctuations in mid-range regions, keeping the GP flexible at edges

## Week 5

In [16]:
x, y = hd.load_and_append(4, 5)

Retrieving inputs/outputs for function 4, week 5
*** Loading new inputs for function 4, week 5 ***

In [17]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (34, 4)
Outputs shape: (34,)

          x1        x2        x3        x4     output
0   0.896981  0.725628  0.175404  0.701694 -22.108288
1   0.889356  0.499588  0.539269  0.508783 -14.601397
2   0.250946  0.033693  0.145380  0.494932 -11.699932
3   0.346962  0.006250  0.760564  0.613024 -16.053765
4   0.124871  0.129770  0.384400  0.287076 -10.069633
5   0.801303  0.500231  0.706645  0.195103 -15.487083
6   0.247708  0.060445  0.042186  0.441324 -12.681685
7   0.746702  0.757092  0.369353  0.206566 -16.026400
8   0.400665  0.072574  0.886768  0.243842 -17.049235
9   0.626071  0.586751  0.438806  0.778858 -12.741766
10  0.957135  0.597644  0.766114  0.776210 -27.316396
11  0.732812  0.145250  0.476813  0.133366 -13.527649
12  0.655115  0.072392  0.687152  0.081517 -16.679115
13  0.219734  0.832031  0.482864  0.082569 -16.507159
14  0.488594  0.211965  0.939178  0.376192 -17.817999
15  0.167130  0.876555  0.217240  0.959801 -26.561821
16  0.216911  0.166086  0.241372  0.770062 -12.758324
17  0.387488  0.804532  0.751795  0.723827 -19.441558
18  0.985622  0.666933  0.156783  0.856535 -28.903274
19  0.037825  0.664853  0.161982  0.253924 -13.702747
20  0.683486  0.902770  0.335420  0.999483 -29.427091
21  0.170347  0.756959  0.276520  0.531231 -11.565742
22  0.859657  0.919592  0.206139  0.097797 -26.857786
23  0.282138  0.505987  0.530531  0.096302  -7.966775
24  0.326076  0.472367  0.453192  0.105887  -6.702089
25  0.948389  0.894513  0.851638  0.552196 -32.625660
26  0.664955  0.046566  0.116777  0.793718 -19.989498
27  0.577766  0.428772  0.425826  0.249007  -4.025542
28  0.738613  0.482103  0.709366  0.503970 -13.122782
29  0.854811  0.493965  0.735310  0.808092 -23.139428
30  0.517002  0.541902  0.438844  0.403496  -3.092031
31  0.536314  0.496395  0.373428  0.460871  -3.297565
32  0.032597  0.410688  0.963138  0.948923 -31.317537
33  0.549933  0.520237  0.414532  0.389236  -3.520409

In [18]:
acquisition = "ei"
beta = 2.0
xi=0.005
noise = 1e-4
length_scale=100
length_scale_bounds=(0.08, 1.0)
n_candidates=20000

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.520295-0.521364-0.423766-0.441290

* update ei to be as originally intended
* xi reduced