# Function 2

Imagine a black box, or a mystery ML model, that takes two numbers as input and returns a log-likelihood score. Your goal is to maximise that score, but each output is noisy, and depending on where you start, you might get stuck in a local optimum.

To tackle this, you use Bayesian optimisation, which selects the next inputs based on what it has learned so far. It balances exploration with exploitation, making it well suited to noisy outputs and complex functions with many local peaks.

In [1]:
FUNCTION_ID=2

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [2]:
x, y = hd.load_and_append(2, 1)

Retrieving inputs/outputs for function 2, week 1

In [3]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (10, 2)
Outputs shape: (10,)

         x1        x2    output
0  0.665800  0.123969  0.538996
1  0.877791  0.778628  0.420586
2  0.142699  0.349005 -0.065624
3  0.845275  0.711120  0.293993
4  0.454647  0.290455  0.214965
5  0.577713  0.771973  0.023106
6  0.438166  0.685018  0.244619
7  0.341750  0.028698  0.038749
8  0.338648  0.213867 -0.013858
9  0.702637  0.926564  0.611205

In [4]:
acquisition = "ucb"
beta = 1.96
noise = 1e-6
length_scale=100

bo = op.BayesianOptimizer(x, y, acquisition=acquisition, beta=beta, noise=noise)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.105988-0.810141

## Week 2

In [5]:
x, y = hd.load_and_append(2, 2)

Retrieving inputs/outputs for function 2, week 2
*** Loading new inputs for function 2, week 2 ***

In [6]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (11, 2)
Outputs shape: (11,)

          x1        x2    output
0   0.665800  0.123969  0.538996
1   0.877791  0.778628  0.420586
2   0.142699  0.349005 -0.065624
3   0.845275  0.711120  0.293993
4   0.454647  0.290455  0.214965
5   0.577713  0.771973  0.023106
6   0.438166  0.685018  0.244619
7   0.341750  0.028698  0.038749
8   0.338648  0.213867 -0.013858
9   0.702637  0.926564  0.611205
10  0.015188  0.897732  0.017946

In [ ]:
acquisition = "ucb"
beta = 1.96
noise = 1e-6
length_scale=100

bo = op.BayesianOptimizer(x, y, acquisition=acquisition, beta=beta, noise=noise)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.974196-0.262033

compared to last week, the only points offered by ucb are 0.99-0.2 tuple
points with ei are 0.7-0.95 ish
both are worth exploring

## Week 3

In [8]:
x, y = hd.load_and_append(2, 3)

Retrieving inputs/outputs for function 2, week 3
*** Loading new inputs for function 2, week 3 ***

In [9]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (12, 2)
Outputs shape: (12,)

          x1        x2    output
0   0.665800  0.123969  0.538996
1   0.877791  0.778628  0.420586
2   0.142699  0.349005 -0.065624
3   0.845275  0.711120  0.293993
4   0.454647  0.290455  0.214965
5   0.577713  0.771973  0.023106
6   0.438166  0.685018  0.244619
7   0.341750  0.028698  0.038749
8   0.338648  0.213867 -0.013858
9   0.702637  0.926564  0.611205
10  0.015188  0.897732  0.017946
11  0.998017  0.267092  0.030991

In [31]:
acquisition = "ucb"
beta = 1.96
noise = 1e-6
length_scale=100
length_scale_bounds=(0.05, 1.0)

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition,
    beta=beta,
    noise=noise,
    length_scale_bounds=length_scale_bounds)

next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.963143-0.000793

## Week 4

In [32]:
x, y = hd.load_and_append(2, 4)

Retrieving inputs/outputs for function 2, week 4
*** Loading new inputs for function 2, week 4 ***

In [33]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (13, 2)
Outputs shape: (13,)

          x1        x2    output
0   0.665800  0.123969  0.538996
1   0.877791  0.778628  0.420586
2   0.142699  0.349005 -0.065624
3   0.845275  0.711120  0.293993
4   0.454647  0.290455  0.214965
5   0.577713  0.771973  0.023106
6   0.438166  0.685018  0.244619
7   0.341750  0.028698  0.038749
8   0.338648  0.213867 -0.013858
9   0.702637  0.926564  0.611205
10  0.015188  0.897732  0.017946
11  0.998017  0.267092  0.030991
12  0.959365  0.996938  0.160769

In [35]:
acquisition = "ucb"
beta = 0.948
noise = 1e-6
length_scale=100
length_scale_bounds=(0.05, 1.0)

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale_bounds=length_scale_bounds)
next = bo.propose()

op.print_next_submission(next)

The next points to be submitted are:
0.443746-0.997845

## Week 5

In [36]:
x, y = hd.load_and_append(2, 5)

Retrieving inputs/outputs for function 2, week 5
*** Loading new inputs for function 2, week 5 ***

In [37]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (14, 2)
Outputs shape: (14,)

          x1        x2    output
0   0.665800  0.123969  0.538996
1   0.877791  0.778628  0.420586
2   0.142699  0.349005 -0.065624
3   0.845275  0.711120  0.293993
4   0.454647  0.290455  0.214965
5   0.577713  0.771973  0.023106
6   0.438166  0.685018  0.244619
7   0.341750  0.028698  0.038749
8   0.338648  0.213867 -0.013858
9   0.702637  0.926564  0.611205
10  0.015188  0.897732  0.017946
11  0.998017  0.267092  0.030991
12  0.959365  0.996938  0.160769
13  0.431959  0.997359 -0.020942

In [38]:
acquisition = "ei"
beta = 1
xi=0.008
noise = 1e-6
length_scale=100
length_scale_bounds=(0.05, 1.0)

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise, 
    length_scale_bounds=length_scale_bounds,
    xi=xi)
next = bo.propose()

op.print_next_submission(next)

The next points to be submitted are:
0.715692-0.941311

This week, switch to EI
* xi set to 0.008, strong exploitation to give promising area

## Week 6

In [39]:
x, y = hd.load_and_append(2, 6)

Retrieving inputs/outputs for function 2, week 6
*** Loading new inputs for function 2, week 6 ***

In [40]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (15, 2)
Outputs shape: (15,)

          x1        x2    output
0   0.665800  0.123969  0.538996
1   0.877791  0.778628  0.420586
2   0.142699  0.349005 -0.065624
3   0.845275  0.711120  0.293993
4   0.454647  0.290455  0.214965
5   0.577713  0.771973  0.023106
6   0.438166  0.685018  0.244619
7   0.341750  0.028698  0.038749
8   0.338648  0.213867 -0.013858
9   0.702637  0.926564  0.611205
10  0.015188  0.897732  0.017946
11  0.998017  0.267092  0.030991
12  0.959365  0.996938  0.160769
13  0.431959  0.997359 -0.020942
14  0.718067  0.943525  0.689719

In [222]:
acquisition = "ei"
beta = 0.05
xi=0.008
noise = 1e-3
length_scale=0.4
length_scale_bounds=(0.07, 1.0)
n_candidates=50000

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale=length_scale, 
    length_scale_bounds=length_scale_bounds,
    xi=xi)
next = bo.propose(n_candidates)

op.print_next_submission(next)

The next points to be submitted are:
0.748265-0.979755

keep it on ei
* noise is increased, after rereading the prompt, I needed to increase it to avoid missing potentially good regions
* length scale increased,
* n_candidates increased