# Function 7

You’re tasked with optimising an ML model by tuning six hyperparameters, for example learning rate, regularisation strength or number of hidden layers. The function you’re maximising is the model’s performance score (such as accuracy or F1), but since the relationship between inputs and output isn’t known, it’s treated as a black-box function. 

Because this is a commonly used model, you might benefit from researching best practices or literature to guide your initial search space. Your goal is to find the combination of hyperparameters that yields the highest possible performance.

In [2]:
FUNCTION_ID=7

""" IMPORTS """
import yaml
import sys
import os
import importlib
sys.path.insert(0, os.path.abspath("../src"))  # adjust if notebook is in notebooks/
import handle_data as hd
import display_data as dd
import optimizer as op

""" reload all files to ensure modified behaviour """
importlib.reload(hd)
importlib.reload(dd)
importlib.reload(op)

""" load config file """
with open("../config/functions.yaml") as f:
    config = yaml.safe_load(f)

cols = config[f"f{FUNCTION_ID}"]["columns"]

## Week 1

In [3]:
x, y = hd.load_and_append(7, 1)

Retrieving inputs/outputs for function 7, week 1

In [4]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (30, 6)
Outputs shape: (30,)

          x1        x2        x3        x4        x5        x6    output
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411

In [5]:
acquisition = "ucb"
beta = 1.96
xi=1
noise = 1e-6
length_scale=100

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.159059-0.636524-0.190377-0.251546-0.436276-0.708447

## Week 2

In [6]:
x, y = hd.load_and_append(7, 2)

Retrieving inputs/outputs for function 7, week 2
*** Loading new inputs for function 7, week 2 ***

In [7]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (31, 6)
Outputs shape: (31,)

          x1        x2        x3        x4        x5        x6    output
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.076540  0.090485  0.401911  0.111218  0.209093  0.981762  0.878128

In [8]:
acquisition = "ucb"
beta = 1.96
xi = 0.005
noise = 1e-4
length_scale=0.1

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale=length_scale,
    xi=xi
)
next = bo.propose()
op.print_next_submission(next)

The next points to be submitted are:
0.047746-0.454964-0.265794-0.224391-0.348566-0.840682

easy, i think its a matter of fine tuning beta for exploration

## Week 3

In [9]:
x, y = hd.load_and_append(7, 3)

Retrieving inputs/outputs for function 7, week 3
*** Loading new inputs for function 7, week 3 ***

In [10]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (32, 6)
Outputs shape: (32,)

          x1        x2        x3        x4        x5        x6    output
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.076540  0.090485  0.401911  0.111218  0.209093  0.981762  0.878128
31  0.030789  0.970133  0.488810  0.032155  0.377123  0.708579  0.188893

In [11]:
acquisition = "ucb"
beta = 2.5
xi = 0.005
noise = 1e-6
length_scale=0.3
n_candidates=20000
length_scale_bounds=(1e-2, 1)

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale=length_scale,
    xi=xi,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates)
op.print_next_submission(next)

The next points to be submitted are:
0.050854-0.803947-0.017139-0.012920-0.522941-0.107199

* beta increased, noise reduced, candidates increased dramatically

## Week 4

In [12]:
x, y = hd.load_and_append(7, 4)

Retrieving inputs/outputs for function 7, week 4
*** Loading new inputs for function 7, week 4 ***

In [13]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (33, 6)
Outputs shape: (33,)

          x1        x2        x3        x4        x5        x6    output
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.076540  0.090485  0.401911  0.111218  0.209093  0.981762  0.878128
31  0.030789  0.970133  0.488810  0.032155  0.377123  0.708579  0.188893
32  0.070576  0.866350  0.007901  0.108149  0.260349  0.079775  0.067732

In [37]:
def lower_bound_15_percent(x):
    """
    Returns a number 15% smaller than the input x.
    """
    return x * (1 - 0.15)

acquisition = "ei"
beta = 2.5
xi = 0.005
noise = 1e-8
length_scale=0.005
n_candidates=20000
length_scale_bounds=(1e-2, 1)
lower_bound = x[:,0].min()
print("Lowest x1:", lower_bound)
lower_bound = lower_bound_15_percent(lower_bound)

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale=length_scale,
    xi=xi,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound)
op.print_next_submission(next)

Lowest x1: 0.030789
The next points to be submitted are:
0.026171-0.425182-0.199356-0.202537-0.437411-0.764153

* switched to ei, want to capitalize on the known optimum
* had to tweek the lower bound. x1 kept giving me 0, so i decided to fix it to the lowest x1 recorded +- 15%

## Week 5

In [39]:
x, y = hd.load_and_append(7, 5)

Retrieving inputs/outputs for function 7, week 5
*** Loading new inputs for function 7, week 5 ***

In [40]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (34, 6)
Outputs shape: (34,)

          x1        x2        x3        x4        x5        x6    output
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.076540  0.090485  0.401911  0.111218  0.209093  0.981762  0.878128
31  0.030789  0.970133  0.488810  0.032155  0.377123  0.708579  0.188893
32  0.070576  0.866350  0.007901  0.108149  0.260349  0.079775  0.067732
33  0.026171  0.298291  0.026171  0.026171  0.420347  0.744344  0.775729

In [56]:
acquisition = "ei"
beta = 2.5
xi = 0.01
noise = 1e-8
length_scale=0.01
n_candidates=20000
length_scale_bounds=(1e-2, 1)
lower_bound = 0

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale=length_scale,
    xi=xi,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.000000-0.405440-0.353154-0.252417-0.423194-0.828518

* kept ei, but tweaked a few params
* lower bound has been reset to 0
* xi is slightly higher to encourage 0.005 more exploration lol
* length_scale has been increased for a slightly smoother model

## Week 6

In [57]:
x, y = hd.load_and_append(7, 6)

Retrieving inputs/outputs for function 7, week 6
*** Loading new inputs for function 7, week 6 ***

In [ ]:
dd.create_and_display_df(x, y, cols)

Inputs shape: (34, 6)
Outputs shape: (34,)

          x1        x2        x3        x4        x5        x6    output
0   0.272624  0.324495  0.897109  0.832951  0.154063  0.795864  0.604433
1   0.543003  0.924694  0.341567  0.646486  0.718440  0.343133  0.562753
2   0.090832  0.661529  0.065931  0.258577  0.963453  0.640265  0.007503
3   0.118867  0.615055  0.905816  0.855300  0.413631  0.585236  0.061424
4   0.630218  0.838097  0.680013  0.731895  0.526737  0.348429  0.273047
5   0.764919  0.255883  0.609084  0.218079  0.322943  0.095794  0.083747
6   0.057896  0.491672  0.247422  0.218118  0.420428  0.730970  1.364968
7   0.195252  0.079227  0.554580  0.170567  0.014944  0.107032  0.092645
8   0.642303  0.836875  0.021793  0.101488  0.683071  0.692416  0.017870
9   0.789943  0.195545  0.575623  0.073659  0.259049  0.051100  0.033565
10  0.528497  0.457424  0.360096  0.362046  0.816891  0.637476  0.073516
11  0.722615  0.011813  0.063646  0.165173  0.079244  0.359952  0.206310
12  0.075665  0.334502  0.132733  0.608312  0.918386  0.822331  0.008826
13  0.942451  0.377440  0.486122  0.228791  0.082632  0.711958  0.268400
14  0.148647  0.033943  0.728806  0.316066  0.021769  0.516918  0.611526
15  0.817112  0.548168  0.103348  0.124370  0.728235  0.449674  0.014798
16  0.417626  0.064100  0.245669  0.559041  0.191531  0.254641  0.274893
17  0.726286  0.464896  0.924571  0.807245  0.635438  0.143418  0.066763
18  0.319810  0.520098  0.290678  0.876707  0.495035  0.619082  0.042118
19  0.879871  0.397962  0.003635  0.956991  0.264514  0.114869  0.002701
20  0.541241  0.631403  0.031902  0.449982  0.798653  0.633704  0.018209
21  0.226348  0.115026  0.824750  0.945384  0.905312  0.951014  0.007016
22  0.686853  0.041017  0.007573  0.285009  0.691568  0.655543  0.100507
23  0.175978  0.624416  0.295542  0.469553  0.097770  0.728141  0.475396
24  0.881647  0.204450  0.414474  0.420385  0.264915  0.730660  0.675142
25  0.066611  0.528045  0.816095  0.961017  0.086509  0.777788  0.516457
26  0.932466  0.488812  0.258608  0.956243  0.190428  0.519852  0.003777
27  0.846867  0.142429  0.060669  0.756292  0.552398  0.081306  0.003134
28  0.806282  0.324122  0.726076  0.148712  0.719376  0.362884  0.021343
29  0.476823  0.340942  0.014335  0.880140  0.998655  0.079664  0.095411
30  0.076540  0.090485  0.401911  0.111218  0.209093  0.981762  0.878128
31  0.030789  0.970133  0.488810  0.032155  0.377123  0.708579  0.188893
32  0.070576  0.866350  0.007901  0.108149  0.260349  0.079775  0.067732
33  0.026171  0.298291  0.026171  0.026171  0.420347  0.744344  0.775729

In [59]:
acquisition = "ei"
beta = 0.35
xi = 0.005
noise = 1e-6
length_scale=0.01
n_candidates=20000
length_scale_bounds=(1e-2, 1)
lower_bound = 0

bo = op.BayesianOptimizer(
    x, 
    y, 
    acquisition=acquisition, 
    beta=beta, 
    noise=noise,
    length_scale=length_scale,
    xi=xi,
    length_scale_bounds=length_scale_bounds
)
next = bo.propose(n_candidates, lower_bound=lower_bound)
op.print_next_submission(next)

The next points to be submitted are:
0.070238-0.542471-0.190235-0.233819-0.396099-0.648450

* kept ei, but tweaked xi by decreasing it by 0.005
    * I want to hone in on the exploitative stage
    * proposed points allign with index 6, by observation, it seems like a smart move